### ISSUE TITLE
Availability of version 0.1.1 of ZINB-WaVE

### ISSUE THREAD

**Issue by twillis209** [drisso/zinb_analysis#5]
Hi there

I am trying to reproduce the paper but I am unable to install v0.1.1 of ZINB-WaVE. I followed the steps in the readme, i.e.

```
library(devtools)
install_github("drisso/zinbwave@v0.1.1")
```

but get the following error

```
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/drisso/zinbwave/tarball/v0.1.1'
```
I cannot locate the tarball at the `zinbwave` repo so I suspect it's no longer available there. Apologies if I'm overlooking something.

Best

**Comment by drisso** [comment]
Hi @twillis209,

after Bioconductor switched to a git-based repository we had to create a new mirror repo that didn't preserve the full history. The old repo, with the full history up to that point is at https://github.com/drisso/archive-zinbwave

So the following code _should_ work (I say should because I haven't tested it myself)
```{r}
library(devtools)
install_github("drisso/archive-zinbwave@v0.1.1")
``` 

Please, note that you should use that version only if you want to reproduce the figures of the paper. Many new features and bug fixes happened in the meantime and our suggestion for new data is to use the latest version of zinbwave.

I hope this helps.

Best,
Davide

**Comment by drisso** [comment]
I will update the README to reflect these changes. Sorry for the trouble!

**Comment by drisso** [comment]
I should add that you probably also downgrade R to version 3.3 and all the Bioconductor packages to the versions compatible with 3.3.

Also note, that most results are likely to be very similar to the paper (but not exactly the same) with newer versions of the package.

**Comment by twillis209** [comment]
That is very helpful, Davide, thank you.
